<a href="https://colab.research.google.com/github/KaushikMuskan/Cloud-Assignments/blob/main/Cloud_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Note: Due to memory limitations, a smaller matrix is used for demonstration.

import numpy as np

rows = 1000   # change to 20000 if system supports
cols = 1000   # change to 10000 if system supports

data = np.random.randint(1, 100, size=(rows, cols))

np.savetxt("data.txt", data, fmt='%d')

print("Data file created")

Data file created


In [ ]:
matrix = [
    [1, 2, 3],
    [0, 0, 0],
    [0, 0, 0]
]

for i in range(1, len(matrix)):
    matrix[i] = matrix[0]

print(matrix)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [ ]:
matrix = [1, 2, 2, 3, 3, 3]

result = []

for i in set(matrix):
    temp = []
    for j in matrix:
        if i == j:
            temp.append(j)
    result.append(temp)

print(result)

[[1], [2, 2], [3, 3, 3]]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


In [ ]:
import numpy as np

n = 3

while True:
    matrix = np.random.randint(1, 10, (n, n))
    valid = True

    for i in range(n):
        for j in range(n):
            if (matrix[i][j] + matrix[n-1-i][n-1-j]) % 2 != 0:
                valid = False

    if valid:
        break

print(matrix)

[[9 7 6]
 [7 6 7]
 [4 7 3]]


In [ ]:
matrix = ((1, 2), (3, 4), (5, 6))

result = []

for row in matrix:
    result.append(sum(row))

print(result)

[3, 7, 11]
